#!/bin/bash

#offline call sign lookup
#11JULY2025

CALL=$1
dir=$HOME/.local/share/fcc_database/
dl=${dir}dl_date
AM=${dir}AM.dat
EN=${dir}EN.dat
version=1.0

if [ -f ${dl} ]; then
  source ${dl}
fi

DOWNLOAD(){
  mkdir -p ${dir}
  echo "downloading"
  cd ${dir}
  mkdir -p old
  mv * ./old/
  wget -U "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" https://data.fcc.gov/download/pub/uls/complete/l_amat.zip
  echo "extracting contents from zip file"
  unzip l_amat.zip
  rm l_amat.zip
  rm CO.dat counts HD.dat HS.dat LA.dat SC.dat SF.dat
  today=$(date +%d-%b-%Y)
  echo last_download=${today} > ${dl}
  echo;echo;echo "usage: fcc <call sign>"
  exit
}

OUTPUT(){
  clear;echo
  echo "-------------------------------"
  echo "FCC Offline Database Tool v${version}"
  echo "Database downloaded ${last_download}"
  echo "-------------------------------"
  echo ${CALL}
  echo "${name}"
  echo "${full_class} class"
  echo ${street}
  echo "${city}, ${state} ${zip}"; echo
  read -p "Call sign or q to quit " CALL

  if [ "${CALL}" = "q" ] || [ ${CALL} = "Q" ]; then
    exit
  fi
  LOOKUP
}

LOOKUP(){
  am_result=$(grep -iw ${CALL} ${AM} | tail -1)
  en_result=$(grep -iw ${CALL} ${EN} | tail -1)

  class=$(echo ${am_result} | awk -F "|" '{print $6}')
  case ${class} in
    T)
      full_class=Technician;;
    G)
      full_class=General;;
    E)
      full_class=Extra;;
  esac
  name=$(echo ${en_result} | awk -F "|" '{print $8}')
  street=$(echo ${en_result} | awk -F "|" '{print $16}')
  city=$(echo ${en_result} | awk -F "|" '{print $17}')
  state=$(echo ${en_result} | awk -F "|" '{print $18}')
  zip=$(echo ${en_result} | awk -F "|" '{print $19}')
  OUTPUT
}

if [ -z $1 ]; then
  echo "usage: fcc <call sign>"
  echo "or"
  echo "usage: fcc download"
  echo "to download latest database"
  exit 1
fi

if [ $1 = "download" ]; then
  DOWNLOAD
fi

if [ ! -d ${dir} ]; then
  echo "ERROR::Database not found!"
  echo "Download database with:"
  echo "fcc download"
  exit
fi
LOOKUP
