#!/bin/bash

#script to install GPS Dongle for Rasperry Pi 3
#Written on pi3 running stretch
#Things changed in Buster. Working on a solution.
#Currently not confirmed working with Buster
#The GPS is working in Buster and can be seen by running cpgs
#However, the time is NOT being pulled from the GPS and passed to 
#the system.
#km4ack 20190911
#Last Edit km4ack 20190920

#install needed packages
echo "installing a few needed packages"
apt-get install -y gpsd gpsd-clients python-gps chrony

#backup gpsd file
mv /etc/default/gpsd /etc/default/gpsd.org

#download gpsd file
wget https://raw.githubusercontent.com/km4ack/pi-scripts/master/gpsd -P /etc/default/

echo "refclock SHM 0 offset 0.5 delay 0.2 refid NMEA" >> /etc/chrony/chrony.conf

#download instructions to pi's desktop
wget https://raw.githubusercontent.com/km4ack/pi-scripts/master/gps-instruction -P $HOME/Desktop

echo "";echo ""; echo ""
echo "#############################################"
echo "#            GPS Instructions               #"
echo "#   Will be on your desktop after install   #"
echo "#############################################"
echo "Reboot is needed to complete"
echo "Would you like to reboot now? y/n"
read ANSW

if [ $ANSW = "y" ]
then
reboot
else
echo "GPS won't work until reboot"
exit 0
fi

