#!/bin/bash

#script to detect if monitor is connected and
#set the correct xorg.conf file.
#huge shoutout to KF7VUT for his work on getting
#this working
#20JULY2023 KM4ACK

CREATE(){
#create the xorg.conf file 
cat <<EOF > /tmp/xorg.conf
Section "Monitor"
  Identifier "Monitor0"
  HorizSync 28.0-80.0
  VertRefresh 48.0-75.0
  # https://arachnoid.com/modelines/
  # 1920x1080 @ 60.00 Hz (GTF) hsync: 67.08 kHz; pclk: 172.80 MHz
  Modeline "1920x1080_60.00" 172.80 1920 2040 2248 2576 1080 1081 1084 1118 -HSync +Vsync
EndSection
Section "Device"
  Identifier "Card0"
  Driver "dummy"
  VideoRam 256000
EndSection
Section "Screen"
  DefaultDepth 24
  Identifier "Screen0"
  Device "Card0"
  Monitor "Monitor0"
  SubSection "Display"
    Depth 24
    Modes "1920x1080_60.00"
  EndSubSection
EndSection

EOF
}

x=0
for file in /sys/class/drm/*; do
    if [ -f $file/status ]; then
        CK=$(grep -w connected $file/status)
    else
        CK=""
    fi

    if [ -n "$CK" ]; then
        echo "monitor connected"
        x=1
        if [ -f /etc/X11/xorg.conf ]; then
            mv /etc/X11/xorg.conf /etc/X11/xorg.conf.bkup
        fi
        break
    fi
done

    #copy xorg.conf file
    if [ $x = 0 ]; then
        CREATE
        cp /tmp/xorg.conf /etc/X11/
    fi
