#!/bin/bash

#09FEB2021 KM4ACK
#script to remove and lock out microsoft repository
#reference - https://www.reddit.com/r/linux/comments/lbu0t1/microsoft_repo_installed_on_all_raspberry_pis/
#reference - https://www.cyberciti.biz/linux-news/heads-up-microsoft-repo-secretly-installed-on-all-raspberry-pis-linux-os/

TEMP=/run/user/$UID/hosts

#Redirect calls to packages.microsoft.com to localhost
cat /etc/hosts > $TEMP
echo "0.0.0.0 packages.microsoft.com" >> $TEMP
sudo cp $TEMP /etc/

#Hold raspberrypi-sys-mods package
sudo apt-mark hold raspberrypi-sys-mods

#remove MS Key file
sudo rm -vf /etc/apt/trusted.gpg.d/microsoft.gpg

#create empty dummy key file
sudo touch /etc/apt/trusted.gpg.d/microsoft.gpg

#lock the dummy key file
sudo chattr +i /etc/apt/trusted.gpg.d/microsoft.gpg

#comment out vscode.list
sudo sed -i 's/deb/#deb/' /etc/apt/sources.list.d/vscode.list

#lock the vscode.list file
sudo chattr +i /etc/apt/sources.list.d/vscode.list

echo "All finished!"
