#!/usr/bin/env bash

set -e

#This script will download the ardop list to the path set below
#It is intended to be run by cron daily
#to keep the list current. km4ack 20181214
#Hint: create a cron job that reads
#30 23 * * * /usr/local/bin/getardoplist
#This script is provided AS IS
#Feel free to mod for your use

#path where files are located
#must match path in findardop script
MYPATH=~/Documents/ardop-list

#make directory if it doesn't exist
mkdir -p $MYPATH

bands="80m 60m 40m 30m 20m 10m 6m 2m 70cm"

#set variables for each list
FILE=$MYPATH/ardoplist.txt

#check internet connection
echo "Please wait while we check your internet connection"
echo "This may take up to a minute"
wget -q --tries=5 --timeout=10 --spider http://google.com
if [[ $? -eq 0 ]]; then
  echo
  echo "Connection Detected"
  echo
  echo "Please wait while files are download"
  echo "This may take several minutes"
  echo "Depending on your internet speed"
else
  echo "YOU ARE NOT CONNECTED TO THE INTERNET"
  exit
fi

for band in $bands
do
  BAND_FILE=$MYPATH/${band}ardoplist.txt

  #remove old files before downloading new ones
  if	[ -f $BAND_FILE ]; then
	  rm $BAND_FILE
  fi

  if 	[ -f $FILE ]; then
	  rm $FILE
  fi

  LAST_DATE=$(date)
  #put date on top line of each file
  echo "List Last Downloaded $LAST_DATE" >> $FILE
  echo "List Last Downloaded $LAST_DATE" >> $BAND_FILE

  #download list to individual files.
  pat rmslist --mode ardop --force-download >> $FILE
  pat rmslist --band $band --mode ardop --force-download >> $BAND_FILE
  echo $band successfully downloaded
done

echo
echo All lists successfully downloaded
